version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npx jest --ci --colclslectCoverage --reporters=jest-junit

reports:
  unittests:
    files:
      - junit.xml
    file-format: JUNITXML
  codecoverage:
    files:
      - 'coverage/cobertura-coverage.xml'
    file-format: 'COBERTURAXML'